### ISSUE TITLE
Gracefully handle permission denial at the splash screen

### ISSUE THREAD

**Issue by ItsHarper** [remotv/controller-for-android#117]
When the user denies a permission at the splash screen, the app always re-requests it. If the user checks the "don't ask again" box before denying, the app hangs at the splash screen.

If the user denies the permission, the app should stop asking for it, and display an error message, with a button to re-request the permission.

**Comment by SkyeOfBreeze** [comment]
![image](https://user-images.githubusercontent.com/4467863/103472054-437d3900-4d4e-11eb-8229-b20f1f743267.png)

**Comment by ItsHarper** [comment]
Looks nice!
