### ISSUE TITLE
Remo is at 5000, Not 3000.

### ISSUE THREAD

**Issue by 770352** [remotv/controller-for-android#39]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel XL]
 - OS: [e.g. Android 9 Pie]
 - App Version [e.g. 0.1.0]

**Additional context**

**Comment by 770352** [comment]
Bug on all devices in all browsers on the repo discription

**Comment by SkyeOfBreeze** [comment]
@770352 Should be fixed now
